name: test_auth_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  shared_preferences: ^2.0.13
  dropdown_search: ^2.0.1
  pinput: ^2.1.4
  flutter_multi_formatter: ^2.5.1
  animations: ^2.0.2
  google_sign_in: '^ 4.5.1' 
  
  flutter:
    sdk: flutter
  get: 4.6.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
